### ISSUE TITLE
Can't download libatsV 0.4.0-17-ga03bec5-SNAPSHOT and libtufV 0.7.1-23-g3ea21d4-SNAPSHOT

### ISSUE THREAD

**Issue by jinlingyi** [simao/ota-lith#1]
There are errors when using sbt docker:publishLocal command, because of downloading the two libs.
If I change them to:
val libatsV = "0.4.0-16-g9328afc"
val libtufV = "0.7.1-24-g846b2c8"
the download error is gone but there will be build errors in source code.

**Comment by simao** [comment]
For libtuf I fixed this in the `master` and `webapp` branches to use the local repo.

For libats you'll need to locally publish the jars.

```
git clone git@github.com:uptane/libats.git
cd libats
git checkout ota-lith
sbt publishLocal
```

And then in the webapp branch of this repo:

```
sbt docker:publishLocal
```

Note that I force pushed to `webapp` so you'll need to reset --hard on that branch.

**Comment by jinlingyi** [comment]
Thank you for your commit!
I can build this project now. But when I run it using sbt or using docker, I met some errors, maybe because my kafka and mysql db configuration error. Do you have some suggestions for how to config kafka and db?

**Comment by simao** [comment]
When you run docker-compose it should start kafka and mysql, which error are you getting on docker-compose?

ota-lith should be built when you do `docker:publishLocal` so you don't need to download it.

**Comment by simao** [comment]
I had forgotten to push a commit changing the webapp image, I pushed it now, the following is working for me now:

```
git clone git@github.com:uptane/libats.git
cd libats
git checkout e903ac1
sbt publishLocal
```

Then on ota-lith, webapp branch: `sbt docker:publishLocal`

Then follow the instructions on the readme to start it using the docker-compose file.

**Comment by simao** [comment]
I just noticed it only worked on the second run, I had to do:

`docker-compose up`, which had the some kafka + mysql errors, but then

`docker-compose down`

and `docker-compose up` worked, I think it was because I had some faulty lingering containers... maybe the same happened with your setup?

**Comment by jinlingyi** [comment]
Yes，I can run it the second time too, using `docker-compose -f ota-ce.yaml up`.
And now I can open `app.ota.ce:9000` in my web browser as a web UI after modify the /etc/hosts.
Thank you for your reply!
Now after I run `./scripts/gen-device.sh` generate a device, and using 'aktualizr --run-mode=once --config=config.toml',
I met some errors of connecting the https://ota.ce:30443 server, I guess it might be the version of my aktualizr?
I will check this issue further on.

**Comment by simao** [comment]
Which errors are you getting when trying to connect? Make sure you are using the right certificates and ota.ce resolves to your machine.

**Comment by jinlingyi** [comment]
I guess the ota.ce is created by a openssl command? I'm not familiar with openssl and I haven't check the issue deeply.
The connection to ota.ce is created but end with a SSL SYSTEM CALL error. The log is on another machine and I will check it tomorrow.

**Comment by simao** [comment]
yeah the certificates are created by those openssl commands, just the machine where aktualizr is running has to know how to resolve `ota.ce` to the ip address of the machine where your docker-compose command is running.

**Comment by jinlingyi** [comment]
I run these servers and aktualizr on a same ubuntu machine. And the resolve of `ota.ce` seems success and a connection is created. My aktualizr is build with the master branch due to the deb can't install on ubuntu 20.04. I will check the error log with creating a new device.

**Comment by jinlingyi** [comment]
By the way, the credentials.zip file generated by get-credentials.sh doesn't contain a  autoprov_credentials.p12 file,
Is that right?

**Comment by simao** [comment]
No, auto provisioning is not an open source feature AFAIK

**Comment by simao** [comment]
I mean, yes that is right that file should not be in a credentials.zip download from ota ce.

**Comment by jinlingyi** [comment]
The connection error log is as below:
```
* Establish HTTP proxy tunnel to ota.ce:30443
> CONNECT ota.ce:30443 HTTP/1.1
Host: ota.ce:30443
User-Agent: Aktualizr/2020.10-37-g2cb76c46
Proxy-Connection: Keep-Alive

< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /tmp/aktualizr-8951-bb55-4f63-7f40/fbb9-3b60-tls-ca
  CApath: /etc/ssl/certs
* CONNECT phase completed!
* CONNECT phase completed!
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ota.ce:30443 
* Closing connection 2
curl error 35 (http code 0): SSL connect error
response http code: 0
response: 
response http code: 0
response: 
response http code: 0
response: 
Flushing report queue
Initializer error: Server error: Error registering device: 0 
```

**Comment by simao** [comment]
That is strange. How are you running aktualizr? What is your config.toml?

gen-device.sh will return a device uuid

after running gen-device.sh you should have a dir `ota-ce-gen/devices/<device-uuid>` and running `aktualizr --config=config.toml` should work.

If that doesn't work, you are probably running different certificate chains on device and server, I'd try creating a new, fresh device and try connecting with that, if that doesn't work, then I'd start from scratch:

```
rm -rf ota-ce-gen/*
rm -rf ota-ce/generated/*
docker-compose -f ota-ce.yaml down
docker volume rm ota-lith_ota-db ota-lith_objects
scripts/gen-server-certs.sh
scripts/gen-device.sh
```

I just tried these steps successfully. If the device cannot connect make sure `ota.ce` points to the correct ip and you don't have any firewall or iptables rules interfering with that connection, on that port.

**Comment by clem844** [comment]
Hi, there is still a version issue with "libats"
I use branch ota-lith of libats to run `sbt publishLocal` and it generates version `0.4.0-27-g7152951` while ota-lith on branch webapp is looking for `0.4.0-20-ge903ac1`
Also, when I change the version in ota-lith to match the one generated, there is still an error as its looking both at the local path `~/.ivy2/local/com.advancedtelematic/` and `~/.ivy2/local/io.github.uptane`

**Comment by simao** [comment]
@clem844 You need to checkout `e903ac1` not the ota-lith branch. That branch has some changes as it's slated to be merged to master at some point. Follow my instructions above: https://github.com/simao/ota-lith/issues/1#issuecomment-876257288

**Comment by clem844** [comment]
This commit does not exist, can you check?

**Comment by simao** [comment]
@clem844 My bad, please try again, you'll need to fetch again or clone new to get it.

**Comment by crab2313** [comment]
Maybe this is the fix of this issue.

https://github.com/wurstmeister/kafka-docker/issues/652#issuecomment-832866851
https://github.com/wurstmeister/kafka-docker/pull/674

> I just noticed it only worked on the second run, I had to do:
> 
> `docker-compose up`, which had the some kafka + mysql errors, but then
> 
> `docker-compose down`
> 
> and `docker-compose up` worked, I think it was because I had some faulty lingering containers... maybe the same happened with your setup?

**Comment by simao** [comment]
See https://github.com/simao/ota-lith/issues/2
