### ISSUE TITLE
hosts file udpate

### ISSUE THREAD

**Issue by bpsrinivas** [simao/ota-lith#4]
Hi 

I am trying to run the project using this method
"Running With Docker Compose"

Here the second step is to 
Update /etc/hosts

I know the question is very basic. Can you let me know what needs to be update in this file ?

I tried adding this in the hosts file
127.0.0.1 app.ota.local
127.0.0.1 gateway.ota.local
127.0.0.1 treehub.ota.local
127.0.0.1 tuf-reposerver.ota.local
127.0.0.1 web-events.ota.local
127.0.0.1 director.ota.ce

but it gives me an error

curl director.ota.ce/health/version
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at director.ota.ce Port 80</address>
</body></html>

**Comment by simao** [comment]
Hi. You have an apache server already running on port 80, that is not part of ota-lith, so you need to disable whatever you are running on that port on your computer before you can start ota-lith using docker-compose.

**Comment by simao** [comment]
You need the following hosts for ota-lith:

```
0.0.0.0         reposerver.ota.ce
0.0.0.0         keyserver.ota.ce
0.0.0.0         director.ota.ce
0.0.0.0         treehub.ota.ce
0.0.0.0         deviceregistry.ota.ce
0.0.0.0         campaigner.ota.ce
0.0.0.0         app.ota.ce
0.0.0.0         ota.ce
```
