### ISSUE TITLE
Code of webapp image

### ISSUE THREAD

**Issue by sydyildirim** [simao/ota-lith#7]
Where can i find the code of webapp image (simaom/ota-plus-web:06053862900a6be6e9b54fe4529e4d1070c98711) on GitHub?

**Comment by simao** [comment]
You can get the code here: https://github.com/simao/ota-plus-server/tree/no-user-profile

This was just the same code as upstream with the user profile patch applied, see https://github.com/advancedtelematic/ota-community-edition/issues/105
